Activity:
    type: entity
    table: activity
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 45
            options:
                fixed: false
        punctuation:
            type: smallint
            nullable: false
            options:
                unsigned: false
                default: '1'
        description:
            type: string
            nullable: true
            length: 1000
            options:
                fixed: false
    lifecycleCallbacks: {  }
