# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        in_memory:
            memory: ~
            
        administrators:
            entity: { class: AppBundle:User } 
            
        # Define o servico que ira fazer a autenticacao
        my_custom_hwi_provider:
            id: my.oauth_aware.user_provider.service
            
    firewalls:
        secured_area:
            anonymous: ~
            oauth:
                resource_owners:
                    facebook:           "/customLogin/check-facebook"
                    google:             "/customLogin/check-google"
                login_path:        /customLogin
                use_forward:       false
                failure_path:      /customLogin

                oauth_user_provider:
                    service: my.oauth_aware.user_provider.service
        
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
            
            
    access_control:
        - { path: ^/customLogin, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/app, roles: ROLE_USER }